### ISSUE TITLE
setuptools should be a dependency

### ISSUE THREAD

**Issue by retrodaredevil** [deepjyoti30/ytmdl#110]
I tried installed this and I got this error:

```
Collecting itunespy==1.5.5 (from ytmdl)
  Downloading https://files.pythonhosted.org/packages/44/c9/88c9b60699ef8e6fad710fcb09352f842298bdf97c110e8279f1d22f292b/itunespy-1.5.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kwd0ydi8/itunespy/
```

I believe setuptools should be a dependency, or should setuptools be a dependency on itunespy?

Of course, this was easy enough to fix by installing setuptools after I figured out what the problem was.

**Comment by deepjyoti30** [comment]
@retrodaredevil  I'm assuming you tried installing through `pip`?? `setuptools` is already a dependency of `ytmdl` and from the log you shared it seems like the installation already started from `ytmdl` as it is trying to install `itunespy`.

However, I cannot say the issue is with `itunespy` but it seems like the issue is occuring due to that itself.

Also, `setuptools` should be installed by default since it is used in order to install other packages from pypi.

Your error is kind of weird, any way you can give me some more insights regarding to it? Something like the OS version and python version and did you do a clean install of the OS etc.

**Comment by retrodaredevil** [comment]
The OS I did this on was Linux Mint 19.3. Before running this, I installed python3-pip and this was the first thing I tried installing with pip (so my guess is that this error is pretty uncommon since people installing this likely have already used pup and installed things that depend on setuputils)

Also, I believe that distutils is available by default, but setuptools is not.

**Comment by deepjyoti30** [comment]
@retrodaredevil Yeah it seems like that was the issue, however I don't think this issue is of ytmdl, it is mostly from `pip` I guess.

Since even if I put `setuptools` as a dependency, the `setup.py` will still import the `setuptools` module before installing the dependencies.

**Comment by retrodaredevil** [comment]
I'll go ahead and close this issue since it isn't really a problem with ytmdl.
