### ISSUE TITLE
"itunes" isn't implemented. Skipping!

### ISSUE THREAD

**Issue by momentai-gbatemp** [deepjyoti30/ytmdl#117]
I keep on getting this error when downloading anything.

**Comment by deepjyoti30** [comment]
@momentai-gbatemp Can you tell me the version of ytmdl you're using as well as how you installed it?!

You can get the version using the `--version` flag.

**Comment by momentai-gbatemp** [comment]
I installed it with AUR and I have version 2020.07.26

**Comment by deepjyoti30** [comment]
@momentai-gbatemp Thanks for reporting the issue. It seems like it is probably occuring due to the last hotfix release I made. I will make a new release shortly that will fix that issue. It is actually caused due to an experimental feature that we were working on.

For now, you can consider installing the git version from AUR. The package is `ytmdl-git`

**Comment by deepjyoti30** [comment]
Fixed in this release
