### ISSUE TITLE
'charmap' codec can't encode characters in position 1-40

### ISSUE THREAD

**Issue by rdesouter** [deepjyoti30/ytmdl#119]
Hello, I try to use the script but here's my error message;

1024 bytes|| ETA: 6 s            
 ==> 'charmap' codec can't encode characters in position 1-40: character maps to <undefined>
 ==> ERROR: 'charmap' codec can't encode characters in position 1-40: character maps to <undefined>

I'm using git bash and pip3 (v.20.2.3)

I've read it's maybe related to Soup (api) convert ASCI to UTF-8, but no idea wich .py file need to be change, can you help me ?

**Comment by deepjyoti30** [comment]
@rdesouter This seems like it is being raised while the file is being downloaded. It might be caused by `youtube-dl` which is internally handling the downloads.

Can you give the logs by running the program with `--DEBUG`?!

**Comment by rdesouter** [comment]
Same
![image](https://user-images.githubusercontent.com/10233095/95084220-de4d8380-071d-11eb-8489-da2db6e48cf3.png)
Although youtube-dl works fine

**Comment by deepjyoti30** [comment]
@rdesouter Can you also tell me how you install `ytmdl` and `youtube-dl`? I understand the issue is occuring while the download so it is probably something that happening because of `downloader-cli` or perhaps even `ytmdl`.

Given that you're using git bash, it's hard for me to exactly reproduce the issue so that's another thing. Do you have any Linux machine that you can test if ytmdl is working or not?
