### ISSUE TITLE
Allow downloading and splitting compilation videos by chapters

### ISSUE THREAD

**Issue by el-banan** [deepjyoti30/ytmdl#131]
# Feature Request

## Checklist

[x] I've searched the bugtracker for similar feature requests including closed ones.
[x] I will add the enhancement label to the issue.

## Description

YouTube now displays chapters in some compliation videos, it would be quite useful to be able to download those videos like playlists are downloaded.
Example video with chapters: https://www.youtube.com/watch?v=Yxd-X8P-GtY

**Comment by el-banan** [comment]
I'd be willing to work on this feature, but I'd really could use some directions in terms of code structure

**Comment by deepjyoti30** [comment]
@el-banan Seems like a neat addition. However this would be a big addition.

Since you asked for directions. Here's how I would try to do it:

When ytmdl recieves a link, it first checks if it is a video or a playlist. Once this is passed, ytmdl accordingly uses  the `youtube-dl` module to extract the videos  in that list and then returns a list of videos. 

The above is similar for a video. ytmdl uses the URL to extract info using the `youtube-dl` module and accordingly returns the song.

Now here's what you can do. Just before the video is returned as a normal video, you can do some checks and verify if it contains chapters. If it **does** contain chapter, you can extract the chapters and make it seem like a list of videos instead of one sole video.

Once you return this list, ytmdl will consider it as a playlist and work accordingly.

**The main difficulty**: Since `ytmdl` uses `youtube-dl`'s api in order to get information about the video, we cannot add support for this if `youtube-dl` doesn't already support it (I'm not sure if they do or not, will have to do some research).

I will reply to this post if I'm able to find some ideas about it but at the moment this feature seems like something we cannot implement right out of the box. 

Also there's another difficulty, the video in the above is considered as one video which means ytmdl would have to split the video into different videos (which might be costly since calls will be made to ffmpeg), fetch metadata for each and then add it to the video.

**Comment by el-banan** [comment]
Looks like youtube-dl is going to add support for chapters based splitting https://github.com/ytdl-org/youtube-dl/pull/25005

**Comment by deepjyoti30** [comment]
@el-banan Looks good, let's wait for the feature to hit a release!

**Comment by deepjyoti30** [comment]
@el-banan Just checked passing the URL to the `youtube-dl` 's `extract_info` method and it seems like it is already returning the chapters along with duration. Seems nice but we will have to use ffmpeg to split the chapters and accordingly get the metadata for each title.

**Comment by deepjyoti30** [comment]
@el-banan I have added the functionality. Please consider installing the latest commits from the `unstable` branch and try it out.

It recognizes the songs automatically if they have chapters and accordingly extracts each song. Since the song you provided was like 2 hours, it was not possible for me to download each song.

Also, most of the song titles are not proper, thus it might fail to search proper meta, for that you can use the `--skip-meta` or `-m` flag.

If you do have any other example video that might be of a smaller length and would have proper song names, feel free to drop the link here, I will give it a try.

In the meantime, do try out the commits and report back if you find any bugs.

**Comment by deepjyoti30** [comment]
Added in `2021.1.14`.

**Comment by crides** [comment]
Is there any option to turn off this feature? I'm on `2021.01.14`, and I do see songs with chapters in them get splits automatically, but I don't want that for some videos (like mixes). I don't see a option in the manual to turn this off, and I'm not quite sure which commit to look into (there's no linked commit here)

**Comment by deepjyoti30** [comment]
@crides There's no flag to disable that feature. As of this release, if the video is recognized as containing split chapters, it will split them automatically. If you want a flag like that you can raise a feature request. I can add it in the next release.
