### ISSUE TITLE
Add ability to skip item when using --list

### ISSUE THREAD

**Issue by drivenbyentropy** [deepjyoti30/ytmdl#151]
# Feature Request

## Checklist

- [x] I've searched the bugtracker for similar feature requests including closed ones.
- [x] I will add the enhancement label to the issue.

## Description
Fist off, thank you for this awesome project, it has huge potential and fills a long needed feature-gap youtube-dl currently does not provide. I have a small suggestion for future implementation. When using the application with the ``--list`` option, I have encountered a situation where ytmdl is unable to find a matching song for me to download. However, there is currently no option to simply skip to the next item in the list, but I am instead forced to select and entry from the presented entries. Adding the capability to skip (e.g. in addition to listing additional matches by pressing 0) would be of great advantage to the user. 

Please feel free to close this issue should this is already be implemented. 

Thanks and all the best!

**Comment by deepjyoti30** [comment]
@drivenbyentropy I think that would be a valid feature since even I have faced something like that in the past. So are you suggesting a feature that will allow the user to skip the song when the user is asked to choose from a list of songs?

How about something like this:

When the user is asked to select an option out of the various video options, if the user selects `-1`, that song is skipped.

**Comment by drivenbyentropy** [comment]
@deepjyoti30 yes, that is exactly my thinking as well. Your suggestion for skipping a song with ``-1`` is great and does not disrupt the overall execution flow.

**Comment by deepjyoti30** [comment]
@drivenbyentropy Should be added in 912029f Consider trying out that commit and report back if it doesn't work.
