### ISSUE TITLE
Override Country when searching iTunes

### ISSUE THREAD

**Issue by kOchirasu** [deepjyoti30/ytmdl#173]
# Feature Request

## Checklist

- [x] I've searched the bugtracker for similar feature requests including closed ones.
- [x] I will add the enhancement label to the issue.

## Description
Some songs are not in US iTunes and won't show up in metadata search. Would be nice to allow the country to be specified.

Describe the feature
Need to pass `country` here: https://github.com/sleepyfran/itunespy/blob/master/itunespy/__init__.py#L126-L127

**Comment by kOchirasu** [comment]
I tried this locally but this doesn't seem to solve my problem. Song's actually seem to be available globally, there's just some translation for text. Will close since I don't think this change is necessary,

**Comment by deepjyoti30** [comment]
@kOchirasu Thanks for the feature request. Even tho this might seems like unnecessary, I think I can add this functionality since this will help users access the meta more easily.

I think I can add a flag for the config that will be checked when ytmdl runs and will accordingly be passed to `itunespy`.

Thanks for the useful links tho!

**Comment by deepjyoti30** [comment]
@kOchirasu I have worked on adding the feature.

The country can be set from the config file. I tried passing different countries from a python script and the results varied so it will be helpful to find local songs.

However, in order to test it with ytmdl, consider setting the `METADAT_PROVIDERS` to `itunes` so that only the results from itunes are shown.

You can report back here if you find any issues with the implementation. I'll merge this code to `unstable` soon!

**Comment by kOchirasu** [comment]
This is one more thing missing because you are not passing country for itunes lookup by id. It should also be passed in here:
https://github.com/deepjyoti30/ytmdl/blob/unstable/ytmdl/metadata.py#L93

**Comment by deepjyoti30** [comment]
@kOchirasu Thanks for the heads up. I updated the code!
