### ISSUE TITLE
Fails when ~/Music does not exist.

### ISSUE THREAD

**Issue by mhoekveen** [deepjyoti30/ytmdl#18]
The script currently errors with a FileNotFoundError when the Music directory does not exist in the home directory.

To reproduce on default configuration:

1.  (re)move the Music directory from your home directory (if exists)
2. run `ytmdl any song`
3. observe the error

I think it would probably be best to not assume the existance of any folders in the home directory and by default just download to the current working directory, unless specified otherwise in user-specific configuration.

**Comment by deepjyoti30** [comment]
Hey @mhoekveen I'll rollout a fix for that ASAP. I'll try to patch all the issues soon and roll out a new release. Sorry for the issue.

**Comment by nyc** [comment]
Two other options for this issue:

1. Download the files to `$SONG_DIR/ytmdl` since users have already configured a folder for where to store the music.
2. Not sure how common this is, but I have a `~/.config/user-dirs.dirs` file defining a `XDG_MUSIC_DIR` for where my music should go, since I don't like the default `~/Music`, so you could try to parse that file. Firefox also uses this file for finding where downloads should go.

Thanks for the hard work on the tool btw!

**Comment by deepjyoti30** [comment]
Yup. The next update will download the temp song to the ```.cache``` dir and after everything is done it will be moved to:

The process will follow as below in order

- Get the dir in config, if not present or invalid, try to get fallback dir's
- Here, the first preference is ```XDG_MUSIC_DIR```
- Else try to fallback to ```~/Music```
- Else move to the current directory
