### ISSUE TITLE
ERROR: Sign in to confirm your age

### ISSUE THREAD

**Issue by 89z** [deepjyoti30/ytmdl#191]
~~~
pip install git+https://github.com/deepjyoti30/ytmdl
PS C:\> ytmdl https://www.youtube.com/watch?v=Cr381pDsSsA
>>
 ==> Searching to see if already present in C:\Users\Steven\Music
 ==> Searching Youtube for https://www.youtube.com/watch?v=Cr381pDsSsA
 ==> Choose One (One with [M] is verified music)
 [1] Some Girls from Equestria have a Fall Formal Fuck-up by Liquid Sky with dur 15:59
 ==> Enter Choice (1): 1
 ==> Downloading Some Girls from Equestria have a Fall Formal Fuck-up in 320kbps
 ==> Saving the files to: C:\Users\Steven\.cache\ytmdl
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
~~~

**Comment by deepjyoti30** [comment]
@89z This seems like an `youtube-dl` error. Ofcourse the error is indicating the video on YouTube requires the user to verify their age (basically sign in) so this means you'll have to pass some session cookies to `youtube-dl` (not sure if they have something like that).

Anyway, I can add support to pass something like session cookies to `youtube-dl` if they support it but without that I really cannot do anything since the issue actually originated in the `youtube-dl` package.
