### ISSUE TITLE
--skip-meta doesn't current work

### ISSUE THREAD

**Issue by jasondlouw** [deepjyoti30/ytmdl#194]
# Version Info 
YTMDL - Latest
YTDL - Latest

# Installation Method
Latest GitHub release (ytmdl-git from AUR)

# Issue
Running ytmdl with the --skip-meta flag still asks for a metadata selection.

This is frustrating because some of the music I am downloading cannot be found through any of the agents and thus I can't move onto the next song. 

This is an amazing project, thank you for all the hard work.

**Comment by deepjyoti30** [comment]
@jasondlouw Thanks for reporting the issue.

I just tested the latest version on my machine and the `--skip-meta` flag worked all right.

Can you tell me how exactly you ran the command? Was it with just one song or did it happen when you tried downloading a playlist?

Also, the `-git` version on `AUR` looks updated.

Can you share the version of `ytmdl` by running `ytmdl --version`?

**Comment by jasondlouw** [comment]
Thank you for the reply

I've only tried running the --skip-meta flag with a playlist and it prompts for a metadata selection.

# Config

I currently use the default config from `https://raw.githubusercontent.com/deepjyoti30/ytmdl/master/examples/config` the only values that have been changed are:
* DEFAULT_FORMAT = "opus"
* Added musicbrainz option as a metadata provider
* Used the suggested advanced SONG_DIR option but remove the `->Title` section as I don't want a separate folder for each song
    * `SONG_DIR = "/mnt/Data/Media/Music$Artist->Album"`

# Command

An example of an exact command is:
`ytmdl --skip-meta https://music.youtube.com/playlist\?list\=OLAK5uy_mbL6q4Z3wuRoamjkP3-AZHLMQFtQHQvR0`

Example output:
```
ytmdl --skip-meta https://music.youtube.com/playlist\?list\=OLAK5uy_mbL6q4Z3wuRoamjkP3-AZHLMQFtQHQvR0
 ==> Youtube playlist passed...extracting!
 ==> Playlist: Album - SYML
 ==> 12 songs found
 ==> Searching to see if already present in /mnt/Data/Media/Music
 ==> Downloading Clean Eyes in 320kbps
 ==> Saving the files to: /home/arch/.cache/ytmdl
3 MB   | 3 Mb/s || ETA: 5 s                   |▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓| 100% ==> Downloaded!
 ==> [Errno 2] No such file or directory: '/mnt/Data/Media/Music$Artist->Album/Clean Eyes.opus'
 ==> Getting song data for Clean Eyes...
 ==> Setting data...
 ==> Choose One
 [1] Clean Eyes by Rancho Relaxo
 [2] Clean Eyes by SYML
 [3] Clean Eyes by SYML
 [4] Clean Eyes by Christdriver
 [5] Clean Eyes (acoustic) by SYML
 [0] More results
 ==> Enter Choice (1): 
```

# Version

The output of `ytmdl --version` is `2021.06.26-1`

# Other

I will the manual installation method and see if I have more luck with that.

**Comment by deepjyoti30** [comment]
@jasondlouw It's very weird, I just tried the playlist you provided and passed the `--skip-meta` option and it worked all fine!

**Comment by deepjyoti30** [comment]
Can you try passing the `--skip-meta` option after the URL

```console
ytmdl https://music.youtube.com/playlist\?list\=OLAK5uy_mbL6q4Z3wuRoamjkP3-AZHLMQFtQHQvR0 --skip-meta --pl-end 1 --pl-start 1
 ==> Youtube playlist passed...extracting! 
 ==> Playlist: Album - SYML 
 ==> 1 songs found 
 ==> Searching to see if already present in /home/deepjyoti30/git/ytmdl 
 ==> Downloading Clean Eyes in 320kbps 
 ==> Saving the files to: /home/deepjyoti30/.cache/ytmdl 
3 MB   | 1 Mb/s || ETA: 3 s       |▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓| 100% ==> Downloaded! 
 ==> Moved to /home/deepjyoti30/git/ytmdl... 
 ==> Done
```

**Comment by jasondlouw** [comment]
So I thought "Why not" and deleted `~/.config/ytmdl` and `~/.cache/ytmdl` and it is now working as expected. There must have been something weird happening somewhere there...

Thank you for you assistance

**Comment by jasondlouw** [comment]
After some testing it seems that if I make any change to my `~/.config/ytmdl/config` it breaks the --skip-meta flag on my system but running the default config works without issue.

**Comment by deepjyoti30** [comment]
@jasondlouw Can you share your config that's causing the error?

**Comment by jasondlouw** [comment]
I have only changed the SONG_DIR option

https://raw.githubusercontent.com/jasondlouw/test/main/config

**Comment by deepjyoti30** [comment]
@jasondlouw I was able to find the issue.

When you try to use advanced path naming (like the one you have above with `SONG_DIR = "/mnt/Data/Media/Music$Artist->Album->Title"`, it is important that the file has metadata too because details like `Artist Name` etc are from metadata.

This is how `ytmdl` functions (in a nutshell):

- Check if `--skip-meta` is passed. If it is, then try to do a dry cleanup (in a dry cleanup, the file is basically copied to the destination without adding any metadata). Once done, *exit*!
- Else continue with metadata addition.

In your case, the destination is a dynamic directory (`/mnt/Data/Media/Music$Artist->Album->Title`), so the *dry cleanup*, fails, as a result, `ytmdl` continues to the next part of the code (adding metadata).

Thus you face this issue.

I will add a fix to disable dry cleanup if the directory is dynamic (or use fallback if dry cleanup is being used).

However, if you want to use the dynamic directory feature but you don't want to enter meta for a few songs, you can go for the `manual` metadata option.

You can also use the `manual` as a fallback using the `ON_META_ERROR` flag.

However, there's no way you'll get the song saved dynamically if you are opting to skip the metadata!

**Comment by deepjyoti30** [comment]
@jasondlouw The issue is fixed from my end. If you use the latest commit from the `unstable` branch or wait 2 days for a new release, the `skip-meta` not working will stop.

However, as I said, you would still not get the song in a dynamically created directory, instead it's base will be used as a fallback!

**Comment by deepjyoti30** [comment]
@jasondlouw Changes should be available in the latest release!

**Comment by jasondlouw** [comment]
Thank you greatly for your assistance!

The lack of dynamic directories with `--skip-meta` is actually ideal for me as I use the MusicBrainz Picard application to add metadata and sort my library in any case.

**Comment by deepjyoti30** [comment]
@jasondlouw I'm glad it's not a problem for you!
