### ISSUE TITLE
Pass flags instead of using config file

### ISSUE THREAD

**Issue by TheCatster** [deepjyoti30/ytmdl#196]
I'm not sure if this is a feature already, but it isn't one that I've seen. I'm writing a quick bash script to take care of a few playlists, and I'd like them to work without intervention in my given directory. The issue is, the directory I want (as an example) is `./music/playlists/<playlist name>`. I thought that I could pass `SONG_DIR` as an env var, but that seems to be completely ignored.

Could support for this be added? Thank you!

**Comment by deepjyoti30** [comment]
@TheCatster That can be a good addition, however there are already various fallbacks for the `SONG_DIR` value.

Reading from the `environment` might not be a preferred way since it can cause issues if some other program sets the value. Plus, I don't think reading flags from the environment is a preferred option by CLI applications.

However, I can add a flag to specify the `song_dir` value that will be given preferrance over everything else!

In the meantime, can't you just make your script update the value of `SONG_DIR` just before it starts working with `ytmdl` and then set it to the older value once the task is done?

Something like the following:

```sh
# Comment every line that is a `SONG_DIR` value
sed -i '/^SONG_DIR/ s/^/#/' ~/.config/ytmdl/config

# Now add your temporary SONG_DIR value
echo "SONG_DIR = ./music/playlists/<playlist name>" >> ~/.config/ytmdl/config

# ------------
# Do your task
# ------------

# Now remove the line that contains the temporary SONG_DIR value
# This line should be the last line since we appended it.
sed -i '$ d' ~/.config/ytmdl/config

# Now uncomment the first SONG_DIR value found in the config
sed -i '0,/^#SONG_DIR/s//SONG_DIR/' ~/.config/ytmdl/config
```

**Comment by TheCatster** [comment]
I'm honestly not sure if it's a preferred way or not, it just seemed more convenient. And absolutely I can do that, I was just trying to find a cleaner implementation.

If the name is specific enough (i.e. `YTMDL_SONG_DIR`) I don't think conflicts would occur. Another question alongside this would be, can I move that config to be in the same directory as the script, or does it have to stay in `XDG_CONFIG_HOME`?

**Comment by deepjyoti30** [comment]
@TheCatster The config will have to stay in `XDG_CONFIG_HOME`.

I think the specific name solution might work! I'll revisit this before the next release!
