### ISSUE TITLE
Youtube playlist downloads - No matches found

### ISSUE THREAD

**Issue by block6791** [deepjyoti30/ytmdl#204]
# How to download playlists at once?

## Checklist
Just installed this on Manjaro. Downloading single videos for music extraction works fine, including the metadata. However, when I paste a link to a YouTube playlist, I get the error "no matches found". For example, downloading this public playlist from a Linux YT channel (just an example) fails:

ytmdl https://youtube.com/playlist?list=PLqmbcbI8U55EQLnXs1ehDw5-D94vloCzb 
zsh: no matches found: https://youtube.com/playlist?list=PLqmbcbI8U55EQLnXs1ehDw5-D94vloCzb

I tried various playlists but none are working.

## Question
How can I download entire playlists? What is the correct way of doing this? Can someone provide an example?

**Comment by deepjyoti30** [comment]
This is not a `ytmdl` error. As you can see it says `zsh: no matches found`. That indicates the shell wasn't able to find any matches.

This is happening because the URL you passed contains certain characters that's making zsh thing it's a command. In order to let zsh know that it's an argument to the previous command, i:e `ytmdl`, you need to pass it as a string in the following way:

```sh
ytmdl "https://youtube.com/playlist?list=PLqmbcbI8U55EQLnXs1ehDw5-D94vloCzb"
```

**Comment by block6791** [comment]
Thanks for the clarification. It works now!
