### ISSUE TITLE
Error when trying to update ytmdl using "pip install ytmdl --upgrade"

### ISSUE THREAD

**Issue by ysahith** [deepjyoti30/ytmdl#214]
# Question

## Checklist

- [x] I've looked through the README and the WiKi for something similar.
- [x] I tried talking with the developer on the Telegram support group.

## Question

![ytmdl_error](https://user-images.githubusercontent.com/47392327/151881699-65c33268-a543-4074-ad07-a2a2d0e44b87.png)

Write question here
Do you know what may be causing this issue?

P.S - Current version of ytmdl functionally works perfectly fine, however I would like to update it.

**Comment by deepjyoti30** [comment]
@ysahith The error is probably not occurring while installation but while uninstalling.

I would like to know the following things:

1. How did you install the current installed version of `ytmdl`? Was it through a package manager or `pip`?
2. Could you try uninstalling `ytmdl` using `sudo pip uninstall ytmdl`. If it fails, try some other package and check if the same error is showing up for that package.

As far as I understand, this error seems unrelated to `ytmdl` and more related to your OS.

**Comment by ysahith** [comment]
1. It has been awhile since I have installed it so I do not recall exactly.

2. I have tried uninstalling with pip using that command and it gives the following error:
![ytmdl_uninstallError](https://user-images.githubusercontent.com/47392327/152231175-5b5241b8-e820-4e7d-badb-87e5d5f439fe.png)

So, how can I uninstall ytmdl manually (so that I can attempt to reinstall with pip)?

**Comment by deepjyoti30** [comment]
Very weird error. I have never seen this error with `ytmdl` before.

At the top of my head, do you have multiple Python versions installed that are somehow conflicting with each other?

Manually removing `ytmdl` would be removing the package files from wherever they are installed to and removing the files from the `bin` directory (wherever it was installed to depdending on your system).

Btw, by any chance did you happen to remove `ytmdl` files before? It's possible that the above error is happening because some files of the package were removed before and now it cannot be removed altogether.

Apologies for the late reply though, totally didn't see your reply on the issue and been stuck with work lately!
