### ISSUE TITLE
Youtube thumbnail as album cover by default

### ISSUE THREAD

**Issue by sinchxn** [deepjyoti30/ytmdl#234]
# Feature Request

## Checklist

- [ ] I've searched the bugtracker for similar feature requests including closed ones.
- [ ] I will add the enhancement label to the issue.

## Description
Giving the option to add the youtube videos thumbnail as the default album cover, as some music videos juust have a static image that could be used as the album cover. 
it could be implemented using something like: 
https://i1.ytimg.com/vi/<insert-youtube-video-id-here>/sddefault.jpg

**Comment by deepjyoti30** [comment]
@sinchxn This is a nice option but I can hardly see a scenario where users would want to download a song from Youtube without metadata and use `ytmdl` for that.

That is basically just using `youtube-dl` through ytmdl.

Also the aim of `ytmdl` is to **provide** metadata for every song downloaded from YouTube so this also is kind of anti what ytmdl is doing.

I am aware that there are cases where the user might want to skip adding the metadata and in those cases I am not sure if adding the default cover would be as useful.

The way `ytmdl` is structure is that if metadata is to be added, it will do it from proper source like iTunes. In such a case, there's no point in adding a default cover if the user entirely choses to skip adding the metadata. On the other hand, if the user wants to add metadata, they can get it from valid sources directly rather than using YouTube's thumbnail.
