### ISSUE TITLE
Video downloader app 


### ISSUE THREAD

**Issue by KalpanaChetan** [deepjyoti30/ytmdl#246]
Please create video playlist downloader app with schedule feature

**Comment by deepjyoti30** [comment]
Hey @KalpanaChetan Thanks for the request, however this cannot be considered an enhancement at this point since it strides too away from the main purpose of `ytmdl` which is to let users extract audio from youtube along with metadata from other sources.

You can perhaps take a look at `yt-dlp` which might suit your needs though I am not sure if they have a schedule feature.
