### ISSUE TITLE
Filename control from CLI

### ISSUE THREAD

**Issue by radoslav006** [deepjyoti30/ytmdl#273]
# Feature Request
It will be very useful to have filename control from a cli.

## Checklist

- [x ] I've searched the bugtracker for similar feature requests including closed ones.
- [ x] I will add the enhancement label to the issue.

## Description
This feature will be as simply as adding new option `--file-name`.  

It is strange to not have the possibility to control file name with command option.  
Moreover, the ytmdl sometimes does not recognize the tags or fails with filename not allowed characters (like '?' or '/'), so it will be the best to have possibility to set every filename.  
My use case is running ytdml from my python script using subprocess module. It will be very convenient to have full control over a filename through cli.

**Comment by deepjyoti30** [comment]
You can apply it through config. [Take a look at this part of the README](https://github.com/deepjyoti30/ytmdl#dynamically-storing-songs)

Since you said sometimes it fails with certain special characters: This is not an expected behaviour and `ytmdl` does try to remove as many special characters as it can find but I would suggest you to open a bug report for that so I can add a fix for it.

> My use case is running ytdml from my python script using subprocess module. It will be very convenient to have full control over a filename through cli.
Why don't you just use the `ytmdl` api instead? You will have more flexibility that way and you will be easily able to set the filename and customize a lot more things. Considering you are writing a script in **python**, it's just a better way to use `ytmdl`'s API instead of using a subprocess.

That being said, I don't think a `--filename` functionality will be much useful considering it can be achieved by modifying the config file. If more requests come in for this feature, I can consider it for sure!

**Comment by radoslav006** [comment]
There are two problems with the config in my opinion:
1. You have to modify config file every time you want to change a filename.
2. As the readme says:
```
SONG_DIR field also takes values that are extracted from the song being downloaded
```
The problem is that in my case about half of the music have no tags recognized (it is a music from a niche radio playlists), so in that case the dynamic filename cannot be created (artist / title are not recognized).

Why I use cli? It is just design decision - it is simpler to use ytmdl as a blackbox as in this case it has simple, well defined and documented interface.

I have a peek in the codebase, but for me it is too complex to bother, especially in this particular case - I have to search a while to just find where and how the filename is created. In my opinion there is lack of high level API. If I remember correctly I have to modify the code to be able to set the filename, I cannot pass it as an argument to some high level function.

As a solution for now I just download the song to the temporary folder and then rename and move it to a final location ;)

That just my thoughts :)
Best regards,
Radoslav

**Comment by deepjyoti30** [comment]
@radoslav006 Thanks for the explanation. I understand what your requirement is right now but there was never in the past a request to support this and as such `ytmdl` was designed with keeping user interaction to the least in mind. Thus, there is no direct high level access for the directory.

However, I think I can add this feature in an upcoming release.

**Comment by radoslav006** [comment]
@deepjyoti30  No problem, I just want to share my feedback to improve a tool that I find already very useful. Thank you for your engagement and openness.

**Comment by deepjyoti30** [comment]
Added in the latest release
