### ISSUE TITLE
Download get gets slower over time. 

### ISSUE THREAD

**Issue by paperbenni** [deepjyoti30/ytmdl#30]
I'm on arch, python 3.8, ryzen 7, gtx 1060
The issue occurs with the git version, the aur version and the pip version. 
Whenever I download a song, it starts out with my normal internet speed and once it hits around 15-20%, it gets unbearably slow (going from estimated 10s to 5m and taking even longer). 
Normal youtube-dl works fine, both from the shell and with the python bindings. 
There's no unusual output in the terminal, it just gets very slow.

**Comment by deepjyoti30** [comment]
I've faced the issue too and I think it's rather the youtube URL that we use to download.

I'm pretty sure the downloader is all right, though I'll consider using a different module to download to see if it works differently.

**Comment by deepjyoti30** [comment]
@paperbenni Hey there, after researching a bit, it turns out the slow download issue was because Google puts a rate limit in their download links. However youtubeDL's downloader checks for that and accordingly is able to download without this issue.

I have implemented the download using the YoutubeDL's download algo and should be fixed in the next release.
