### ISSUE TITLE
very slow downloading

### ISSUE THREAD

**Issue by pjhalsli** [deepjyoti30/ytmdl#37]
I really love the idea of his program  - not being forced to leave the terminal to look for songs in a browser  - now you can just stay in the terminal and search from there. Genius. But why is it so slow compared to youtube-dl.

ytmdl was at 80% I then downloaded the same song with youtube-dl and converted it to an audio file. When it was finished ytdml was still at 96% so there's something there that takes a lot of time. It's ok fpr a song or two I guess but if you want to download say 5-6 albums (50-60 songs) it will take a lot of time. Is there a way to speed it up?

**Comment by deepjyoti30** [comment]
@pjhalsli Hey, I am aware of the issue. I have even tried downloading using chrome and it turns out it's the URL that makes the download slower towards the end.

I will have to look into ```youtube-dl``` source code to check how they implement the downloading.

**Comment by deepjyoti30** [comment]
@pjhalsli After a doing a bit of research, it turns out the download was slow because puts a ratelimit on their download links. 

I was using ```downloader-cli``` to download which didn't check for ratelimits. However ```Youtube-dl``` downloader does check that and is able to download faster, so I decided to move to their downloader.

The progressbar and other stuff will still be same with the addition of a faster download. Will be added in the next release.

I'll close the issue once that release is made.

**Comment by deepjyoti30** [comment]
Should be fixed in the latest release.

**Comment by pjhalsli** [comment]
You are THE man

**Comment by deepjyoti30** [comment]
@pjhalsli Thanks!!

**Comment by samuelpetrosyan** [comment]
Still slow download!!?? Is there any solution?

**Comment by deepjyoti30** [comment]
@samuelpetrosyan This issue should be irrelevant to slow downloads if you're using the latest version because after this release, I moved the code to use `youtube-dl` all together for downloads.
