### ISSUE TITLE
Not relevant tag for songs

### ISSUE THREAD

**Issue by ramuskay** [deepjyoti30/ytmdl#52]
Hi,

I have an issue to tag correctly music I downloaded, below there is example : 

[root@pc-root ytmdl]$ ytmdl --song single ladies
 ==> Searching to see if already present in /home/adeschamps/Musique
 ==> Searching Youtube for ladies
 ==> Choose One
 [1] Beyoncé - Single Ladies (Put a Ring on It)
 (Video Version) by Beyoncé with dur Durée 3:19
 [2] Lee Fields & The Expressions - Ladies by franqus with dur Durée 4:18
 [3] Travis Porter ft.Tyga - Ayy Ladies (Official Video) by Travis Porter with dur Durée 3:32
 [4] Kool & The Gang - Ladies Night by soulbrothanumbahone with dur Durée 6:29
 [5] Oryane ft. Sean Paul - Love Mi Ladies (Official Music Video) by Scorpio Music with dur Durée 2:50
 [0] More results
 ==> Enter Choice [a valid choice] 1
 ==> Downloading Beyoncé - Single Ladies (Put a Ring on It) (Video Version) in 320kbps
 ==> Saving the files to: /home/adeschamps/.cache/ytmdl
3 MB   | 1 Mb/s || ETA: 3 s                                                                                                                                                                                                      |▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓| 100% ==> Downloaded!
 ==> Converting to mp3...
 ==> Getting song data for single...
 ==> Setting data...
 ==> Choose One
 [1] Single by The Neighbourhood
 [2] Single by Ne-Yo
 [3] Single by Musiq Soulchild
 [4] Beat It by Michael Jackson
 [5] The Way You Make Me Feel by Michael Jackson
 [0] More results

This song is very famous but the album provided are not accurate (it seems to be based on the song name)
Is this possible to guess the album name from the song name (I don't want to provide the album name) ?
Thank you for your answer

**Comment by deepjyoti30** [comment]
Currently the song name is searched as is in Itunes and other sources for metadata. I just tried with the song you passed and it seems like the song does come up but around 23 place in the metadata.

```[23] Single Ladies (Put a Ring on It) by Beyoncé```

For the time being you can click on more results and go to the part where you'd get the result.

About the bug, it does seem like something is causing the song to go down in the list instead of being at the top since the song is famous. I will look into it ASAP. It might be because of some post processing ```ytmdl``` does with the metadata sources in order to show users the best result.

Thanks for raising the bug.
