### ISSUE TITLE
[Feature] tag without download

### ISSUE THREAD

**Issue by vince2010091** [deepjyoti30/ytmdl#56]
Hello,
Is it possible to tag massively a MP3 folder (without download from youtube)
Regards

**Comment by deepjyoti30** [comment]
@vince2010091 Currently it doesn't support anything like that and I think adding something like that would really take the development in another direction.

However, you can still use the methods in ```ytmdl``` and write a simple Python script to do what you want, it won't be that hard since most of the work would be done by the methods already present in ytmdl.

**Comment by deepjyoti30** [comment]
@vince2010091 I wrote a simple script to the what you're asking for, it uses ytmdl methods so make sure ytmdl is installed.

## What it does
1. Takes a directory as input and scans it for mp3 songs
2. The songs are then moved to ```~/.cache/ytmdl/``` (ytmdl restriction).
3. Then it converts the song to mp3 and adds the tags to the converted song in the ```~/.cache``` directory. 
4. Once the tags are added, the song is moved to a new directory. Set this directory in the ytmdl config file here ```~/.config/ytmdl/config```.

Change ```SONG_DIR``` to the path where you want the final songs. (Please don't use ~ or $HOME since ytmdl yet doesn't support those.)

```Usage: python meta.py [dir where songs are]```

Here's the  code

```python
from ytmdl import metadata, song, dir, utility
from sys import argv
from os import path, listdir
from shutil import copyfile


def set_data(song_name, get_from_user=True):
    """
    Set the data by searching using the passed song name.

    Sometimes the passed song name may not be proper so
    ask the user for a name instead.
    """
    print("Setting for: {}".format(song_name))
    if not get_from_user:
        search_name = path.basename(song_name)
    else:
        search_name = input("Enter the name of the song: ")

    # Get the song info
    track_info = metadata.SEARCH_SONG(search_name)

    # Move the song to ~/.cache/ytmdl
    des = path.expanduser(path.join("~/.cache/ytmdl", path.basename(song_name)))
    copyfile(song_name, des)

    # Convert the song to mp3 as well
    print("Converting the song to mp3 so that it can contain the tags")
    song_name = utility.convert_to_mp3(des)

    # Get a choice from the user
    option = song.setData(track_info, False, path.basename(song_name))
    print(option)

    if type(option) is not int:
        print("Something went wrong.")
        exit(-1)

    # Move the song to the dir
    DIR = dir.cleanup(track_info, option)

    if type(DIR) is not str:
        print("Couldn't move the song.")
        exit(-1)
    else:
        print("Moved to {}".format(DIR))
        print("Added meta to {}".format(song_name))


if __name__ == "__main__":
    if len(argv) != 2:
        print("Usage: {} [directory containing the songs]".format(argv[0]))
        exit(0)

    song_dir = argv[1]

    if not path.exists(song_dir) or not path.isdir(song_dir):
        print("Passed name is not a dir or doesn't exist.")
        exit(-1)

    for file in listdir(song_dir):
        if file.endswith(".mp3"):
            set_data(file)

```
Feel free to make changes as you like.

**Comment by vince2010091** [comment]
@deepjyoti30 Thanks for your feedback, I will look in this direction.
