### ISSUE TITLE
Add MetaData off

### ISSUE THREAD

**Issue by phmassa** [deepjyoti30/ytmdl#68]
can you add an option to disable metadata retrieving

**Comment by deepjyoti30** [comment]
@phmassa I think disabling that would make it just function like ```youtube-dl``` because even they do all the postprocessing of converting the song to an mp3 and all.

Just one thing that ```youtube-dl``` don't do is searching by the passed song name and then downloading, I'll look into what you requested and if possible and feasible, will add it.

**Comment by Ferryistaken** [comment]
I think that it's a very good idea, youtube-dl doesn't allow you to search for a song, you need to provide the whole link, which limits the functionality of that tool. Sometimes the song that I'm searching for isn't very well known so there is no metadata on other sites, which means that after downloading I have to strip metadata from that file if I want it to have the "real" title. You could do something like adding a --no-meta-data flag to make the program entirely skip the metadata fetching part. It's nearly no new code.

**Comment by deepjyoti30** [comment]
@Ferryistaken That's a good suggestion.

I'm thnking if I'm gonna add an option to skip the metadata then I will also add an option to manually set the metadata since the only reason people would choose to skip meta would be, as you mentioned, lack of availability. 

Let's see, I will add it for the next release.

**Comment by Ferryistaken** [comment]
I think that it would be a very good idea only if you keep it simple, something like `ytmdl <songname> --no-metadata(or --manual-metadata) --artist <artistName> --name <songName> --album <albumName>`

**Comment by deepjyoti30** [comment]
@Ferryistaken Yep, that's exactly how I'm working on it, it's almost ready.

**Comment by deepjyoti30** [comment]
@phmassa  @Ferryistaken
Added support in https://github.com/deepjyoti30/ytmdl/commit/adc705537422ca3e1438004fc92f8bd001afbbae

You can try it by installing the latest commits following the manual way.

Report back here in case of issues.

**Comment by deepjyoti30** [comment]
Added in latest release.
