### ISSUE TITLE
Something went wrong while writing data!

### ISSUE THREAD

**Issue by JerryBels** [deepjyoti30/ytmdl#72]
Hi!

I'm using this for a few days and it's awesome. I'm using it from a windows computer. A question though. Sometimes, seemingly for no reason whatsoever, it answers "Something went wrong while writing data!" after choosing the tagging source. Choosing another of the youtube videos and tagging it will then work. 

I wondered if there is a more detailed error log somewhere I could inspect? Curious about why this is happening.

**Comment by deepjyoti30** [comment]
@JerryBels Thanks for reporting, can you try running on debug mode and gimme the logs.

```ytmdl <Name of song> --level DEBUG```

Also the log will be located in ```~/.cache/ytmdl/logs/log.cat```, however since you're using Windows, I'm not sure if you'll be able to locate it so just copy paste the output when running the above command.

Also, do you mind sharing how you are using it on Windows? Is it by using WSL or did you fix the bugs to make it compatible with Windows.

I had actually opened an issue because I want to add support for Windows and need volunteers to gimme logs  so that I can fix the bugs, however seems like people using Windows are not interested.

**Comment by JerryBels** [comment]
Sure, I will, as soon as I have an error again. Using it daily so it won't take long.

But now that I think of it... I used this fork https://github.com/biswaroop1547/ytmdl since you thanked the user for testing on Windows. But I see it has lots of commits missing. Not sure if it's related though. Probably would be interesting to merge.

And if there are bugs, I didn't have any - after installing and installing all dependencies with pip all was set and good.

**Comment by deepjyoti30** [comment]
@JerryBels That is a really old version, I suppose you wouldn't even have things like ```--level```.

I'm afraid I won't be able to help you with the issue if you're using such an old version, however if you want you can help bring support for the latest version since you're an windows user.

If you want, comment on #51 .

**Comment by JerryBels** [comment]
I understand :) I think I will try to install the last version on windows. The problem is, I'm not a python dev (yet, anyway). So I probably won't be able to code anything for a PR :(

**Comment by deepjyoti30** [comment]
@JerryBels Hey, I'm not asking you to code anything, all you need to do is give me the error logs and I'll make changes and you need to install and try, that's it.

I will fix the bugs, I just want you to test and report.

**Comment by JerryBels** [comment]
You're not asking, but I would have loved to! That's what I meant. But of course, I will help. I'm on ubuntu most of the time but have a Windows 7 computer at home yet, which I'm using for some musical games and such. I will use it to test and report.

**Comment by deepjyoti30** [comment]
@JerryBels Let's continue this conversation in the other issue then.

Just try running the latest version and gimme the logs there.
